# install if xtable is not installed
package_name <- "xtable"

if (!require(package_name, character.only = TRUE)) {
  install.packages(package_name, dependencies = TRUE)
  library(package_name, character.only = TRUE)
}

# Save this as generate_r_table.R
library(xtable)

# Create a sample dataframe
r_df <- data.frame(
  ID = 1:5,
  Name = c("Alice", "Bob", "Charlie", "David", "Eve"),
  Score = c(85, 92, 78, 90, 88)
)

# Generate the LaTeX table using xtable
table_output <- xtable(r_df, caption = "Data Table Generated by R")
print(table_output, file = "r_table.tex", type = "latex")
